version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: syncforce
      POSTGRES_PASSWORD: password
      POSTGRES_DB: syncforce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syncforce"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  syncforce-python:
    build: 
      context: ./syncforce-python
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://syncforce:password@db:5432/syncforce
      - JWT_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ENCRYPTION_KEY=N_Gv9d13x7GzU5iA5-wQ3U4M-iH3F3N5R7z0vO0wH9I=
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  syncforce-java:
    build:
      context: ./syncforce-java
    ports:
      - "8080:8080"

volumes:
  postgres_data:
